In [13]:
def solution(a):
    m = len(a)
    n = len(a[0])
    import numpy as np
    b = np.zeros((m,n))
    
    for i in range(m):
        for j in range(n):
            b[j][-i+m-1] = a[i][j]
            
    return b

In [14]:
a=[[1,2,3], 
 [4,5,6], 
 [7,8,9]]

solution(a)

[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 1.]
 [0. 0. 2.]
 [0. 0. 0.]]
[[0. 0. 1.]
 [0. 0. 2.]
 [0. 0. 3.]]
[[0. 4. 1.]
 [0. 0. 2.]
 [0. 0. 3.]]
[[0. 4. 1.]
 [0. 5. 2.]
 [0. 0. 3.]]
[[0. 4. 1.]
 [0. 5. 2.]
 [0. 6. 3.]]
[[7. 4. 1.]
 [0. 5. 2.]
 [0. 6. 3.]]
[[7. 4. 1.]
 [8. 5. 2.]
 [0. 6. 3.]]
[[7. 4. 1.]
 [8. 5. 2.]
 [9. 6. 3.]]


array([[7., 4., 1.],
       [8., 5., 2.],
       [9., 6., 3.]])

In [56]:
def solution(grid):
    m = len(grid)
    n = len(grid[0])
    
    for i in range(m):
        col = []
        for j in range(n):
            if grid[i][j] == '.':
                continue
            elif grid[i][j] not in col:
                col.append(grid[i][j])
            elif grid[i][j] in col:
                return False
            
    for i in range(m):
        rw = []
        for j in range(n):      
            if grid[j][i] == '.':
                continue
            elif grid[j][i] not in rw:
                rw.append(grid[j][i])
            elif grid[j][i] in rw:
                return False
    
    checker1 = []
    checker2 = [] 
    checker3 = [] 
    for i in range(m):
        if i == 3 or i == 6:
            checker1 = []
            checker2 = [] 
            checker3 = []
            
        for j in range(n):
            if j < 3:
                if grid[i][j] == '.':
                    continue
                elif grid[i][j] not in checker1:
                    checker1.append(grid[i][j])
                elif grid[i][j] in checker1:
                    return False
                
            elif j < 6:
                if grid[i][j] == '.':
                    continue
                elif grid[i][j] not in checker2:
                    checker2.append(grid[i][j])
                elif grid[i][j] in checker2:
                    return False
            
            elif j < 9:
                if grid[i][j] == '.':
                    continue
                elif grid[i][j] not in checker3:
                    checker3.append(grid[i][j])
                elif grid[i][j] in checker3:
                    return False
                

        
    return True 

In [57]:
grid=[[".",".",".",".",".",".","5",".","."], 
      [".",".",".",".",".",".",".",".","."], 
      [".",".",".",".",".",".",".",".","."], 
      ["9","3",".",".","2",".","4",".","."], 
      [".",".","7",".",".",".","3",".","."], 
      [".",".",".",".",".",".",".",".","."], 
      [".",".",".","3","4",".",".",".","."], 
      [".",".",".",".",".","3",".",".","."], 
      [".",".",".",".",".","5","2",".","."]]


solution(grid)

Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = 5
check3 = ['5']
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = 9
check1 = ['9']
Entry = 3
check1 = ['9', '3']
Entry = .
Entry = .
Entry = 2
check2 = ['2']
Entry = .
Entry = 4
check3 = ['4']
Entry = .
Entry = .
Entry = .
Entry = .
Entry = 7
check1 = ['9', '3', '7']
Entry = .
Entry = .
Entry = .
Entry = 3
check3 = ['4', '3']
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = 3
check2 = ['3']
Entry = 4
check2 = ['3', '4']
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = .
Entry = 3


False

In [43]:
a = [0,1,2]
for i in a:
    print(i)

0
1
2


In [20]:
def solutiona(crypt, solution):
    keys = []
    for i in range(len(solution)):
        keys.append(solution[i][0])
    
    test = "".join(keys)
    fresults = []
        
    for i in crypt:
        results = []
        for j in i:
            char_index = test.find(j)
            a = str(solution[char_index][1])
            results.append(a)
            
        a = "".join(results)
        fresults.append(a)
    
    if int(fresults[0]) + int(fresults[1]) != int(fresults[2]):
        return False
    
    else:        
        for i in fresults:
            if i[0] == "0" and len(i) >= 2:
                return False
        
    return True

In [21]:
crypt = ["SEND", "MORE", "MONEY"]

solution = [['O', '0'],
            ['M', '1'],
            ['Y', '2'],
            ['E', '5'],
            ['N', '6'],
            ['D', '7'],
            ['R', '8'],
            ['S', '9']]

solutiona(crypt, solution)

True

In [16]:
def solution(s1, s2):
    d1 = dict()
    d2 = dict()
    results = []
    
    for i in range(len(s1)):
        if s1[i] not in d1:
            d1[s1[i]] = 1
        else:
            d1[s1[i]] += 1
            
    for i in range(len(s2)):
        if s2[i] not in d2:
            d2[s2[i]] = 1
        else:
            d2[s2[i]] += 1
            
    if len(d1) > len(d2):
        print(f"d1>d2, d1={d1},d2={d2}")
        for k,v in d1.items():
            if k in d2 and v > d2[k]:
                results.append(d2[k])
            elif k in d2 and v <= d2[k]:
                results.append(v)
                
    elif len(d1) <= len(d2):
        print(f"d1<=d2, d1={d1},d2={d2}")
        for k,v in d2.items():
            if k in d1 and v > d1[k]:
                results.append(d1[k])
            elif k in d1 and v <= d1[k]:
                results.append(v)
    
    print(results)
    return sum(results)

In [17]:
s1="aabcc"
s2= "adcaa"

solution(s1, s2)

d1<=d2, d1={'a': 2, 'b': 1, 'c': 2},d2={'a': 3, 'd': 1, 'c': 1}
[2, 1]


3

In [10]:
def solution(inputString):
    a = inputString.find("(")
    b = inputString.find(")")
    c = inputString[a+1:b]
    d = c[::-1]
    
    for i in range(len(inputString)):
        if inputString[i] == "(":
            b = inputString.find(")")
            c = inputString[i+1:b]
    
    return d
        

In [12]:
inputString = "foo(bar)baz(blim)"
solution(inputString)

'rab'